/**
 * APTITUDE ANSWER KEY — SERVER ONLY (CR-5)
 *
 * This file must NEVER be imported from anything under src/ or reachable from index.tsx.
 * It is consumed only by the `score-aptitude` Supabase Edge Function.
 *
 * Previously `answer` and `explanation` lived inline in
 * src/Interview/services/questionBank.ts, which is bundled into the client. Every candidate
 * could read the correct option for all 80 aptitude questions from DevTools, and
 * scoring was done client-side against that same data.
 *
 * Generated by lifting the fields out of the question bank; regenerate deliberately, not
 * automatically, so that a future edit cannot silently reintroduce them into the bundle.
 */

export interface AptitudeAnswer {
  answer: string;
  explanation: string;
}

export const APTITUDE_ANSWER_KEY: Record<string, AptitudeAnswer> = {
  "apt_q_01": { answer: "B", explanation: "Average speed = Distance / Time = 120 km / 2 hours = 60 km/h." },
  "apt_q_02": { answer: "C", explanation: "Profit = $25 - $20 = $5. Profit % = (5 / 20) * 100 = 25%." },
  "apt_q_03": { answer: "B", explanation: "Together rate = 1/12 + 1/24 = 3/24 = 1/8. So, 8 days." },
  "apt_q_04": { answer: "B", explanation: "Number = 45 / 0.15 = 300. 40% of 300 = 0.40 * 300 = 120." },
  "apt_q_05": { answer: "B", explanation: "First 5 primes: 2, 3, 5, 7, 11. Sum = 28. Average = 28 / 5 = 5.6." },
  "apt_q_06": { answer: "B", explanation: "Let Principal = P. Amount = 2P, so SI = P. P = (P * R * 8)/100 => R = 100/8 = 12.5%." },
  "apt_q_07": { answer: "B", explanation: "Total letters = 6. E is repeated twice. Ways = 6! / 2! = 720 / 2 = 360." },
  "apt_q_08": { answer: "A", explanation: "Probability = (13C1 * 13C1) / 52C2 = (13 * 13) / (26 * 51) = 13/51." },
  "apt_q_09": { answer: "A", explanation: "1.5 m = 150 cm. Ratio = 90 : 150 = 3 : 5." },
  "apt_q_10": { answer: "B", explanation: "Difference = P * (R/100)^2 = 2000 * (10/100)^2 = 2000 * 0.01 = $20." },
  "apt_q_11": { answer: "B", explanation: "Volume = pi * r^2 * h = (22/7) * 7 * 7 * 10 = 1540 cm3." },
  "apt_q_12": { answer: "B", explanation: "12 Men = 18 Women => 1 Man = 1.5 Women. 8 Men + 16 Women = 8*1.5 + 16 = 28 Women. If 18 Women do it in 14 days, 28 Women do it in (18*14)/28 = 9 days." },
  "apt_q_13": { answer: "B", explanation: "Speed in m/s = 54 * (5/18) = 15 m/s." },
  "apt_q_14": { answer: "B", explanation: "Total balls = 14. White balls = 8. Probability = 8/14 = 4/7." },
  "apt_q_15": { answer: "B", explanation: "Cost Price = Selling Price / (1 + Profit Rate) = 115 / 1.15 = $100." },
  "apt_q_16": { answer: "B", explanation: "log 5 = log(10/2) = log 10 - log 2 = 1 - 0.3010 = 0.6990." },
  "apt_q_17": { answer: "C", explanation: "Total outcomes = 8. At least 2 heads: HHH, HHT, HTH, THH (4 outcomes). Probability = 4/8 = 1/2." },
  "apt_q_18": { answer: "B", explanation: "Sum = n*(n+1)/2 = 50*51/2 = 1275." },
  "apt_q_19": { answer: "B", explanation: "Passing marks = 178 + 22 = 200. If 40% = 200, then Max Marks = 200 / 0.4 = 500." },
  "apt_q_20": { answer: "B", explanation: "For half-yearly, periods (n) = 2, rate (R) = 10%. Amount = 10000 * (1.1)^2 = $12100. CI = 12100 - 10000 = $2100." },
  "apt_q_21": { answer: "B", explanation: "(256)^(0.16 + 0.09) = (256)^0.25 = (256)^(1/4) = 4." },
  "apt_q_22": { answer: "B", explanation: "Downstream speed = 13 + 4 = 17 km/h. Time = 68 / 17 = 4 hours." },
  "apt_q_23": { answer: "C", explanation: "Let ages be 5x and 7x. (5x-18)/(7x-18) = 8/13 => 65x - 234 = 56x - 144 => 9x = 90 => x = 10. Ages are 50 and 70." },
  "apt_q_24": { answer: "C", explanation: "Profit = $300. Profit % = (300/1200) * 100 = 25%." },
  "apt_q_25": { answer: "D", explanation: "Initial: Milk = 40L, Water = 20L. To make ratio 1:2, water must become 80L. Water to add = 80 - 20 = 60 liters." },
  "apt_q_26": { answer: "C", explanation: "The pattern cycles back to the first shape (square) to restart the sequence." },
  "apt_q_27": { answer: "C", explanation: "Pattern doubles each time: 2*2=4, 4*2=8, 8*2=16, 16*2=32." },
  "apt_q_28": { answer: "B", explanation: "Mapping: C=4, H=5, A=1, R=6, C=2, O=9, A=1, L=3. Wait, CHARCOAL has C=4 and C=2? Actually CHARCOAL is 45162318 or similar. Let's look at the mapping: C=4, O=2, A=1, L=3. Thus COAL = 4213." },
  "apt_q_29": { answer: "B", explanation: "'My father's son' with no brothers/sisters means 'Myself'. So, the man's father is 'Myself', meaning the photo is of his son." },
  "apt_q_30": { answer: "C", explanation: "Starting East -> turns right (facing South) -> turns left (facing East). He is facing East." },
  "apt_q_31": { answer: "D", explanation: "Since E, B, C, D are opposite each other, their exact seats are E opposite B, C opposite D. This leaves two seats for A and F, with F to the immediate left of A. We don't have enough constraints to place E relative to them, so it cannot be determined." },
  "apt_q_32": { answer: "B", explanation: "Alternate letters (A, C, E, G, I) and their alphabetical positions (1, 3, 5, 7, 9). So, I9." },
  "apt_q_33": { answer: "C", explanation: "Each letter is replaced by its preceding and succeeding letter. C -> BD, A -> BZ, T -> SU. CAT -> BDBZSU." },
  "apt_q_34": { answer: "C", explanation: "27 (3^3), 64 (4^3), 125 (5^3), 216 (6^3) are cubes. 144 (12^2) is a square." },
  "apt_q_35": { answer: "D", explanation: "None of the choices specify P's gender or correct relationship structure to define P as a nephew of Q. Thus, Cannot be determined." },
  "apt_q_36": { answer: "B", explanation: "Each row increases the shape count by 1. Row 3 has 1 square, 2 squares, so the third element is 3 squares (□□□)." },
  "apt_q_37": { answer: "A", explanation: "A person can be a writer, researcher, and teacher simultaneously, or any combination of the two. This is best represented by three intersecting circles." },
  "apt_q_38": { answer: "C", explanation: "Milk is white, and 'White' is called 'Black', so the answer is Black." },
  "apt_q_39": { answer: "D", explanation: "Difference doubles: +2, +4, +8, so next is +16. 17 + 16 = 33." },
  "apt_q_40": { answer: "C", explanation: "Since all mangoes are golden and no golden is cheap, mangoes are not cheap. Conclusions I and II are false." },
  "apt_q_41": { answer: "A", explanation: "A mirror to the right reverses the order and flips the letters horizontally: Y, S, A, E all reversed, starting with Y." },
  "apt_q_42": { answer: "D", explanation: "Wink is a fast action of the eye; beat/throb is the action of the heart. Beat is the primary match." },
  "apt_q_43": { answer: "A", explanation: "Step backward by 2 letters: Z -> X -> V -> T -> R -> P." },
  "apt_q_44": { answer: "A", explanation: "At 3:00, minute hand is at 12 (pointing N-E) and hour hand is at 3 (90 degrees clockwise). 90 degrees clockwise from North-East is South-East." },
  "apt_q_45": { answer: "A", explanation: "An ordinary year starts and ends on the same day of the week." },
  "apt_q_46": { answer: "C", explanation: "Row pattern: x, x^2, x^3. Row 3 is 4, 16, 4^3 = 64." },
  "apt_q_47": { answer: "A", explanation: "The operator doubles the shape horizontally." },
  "apt_q_48": { answer: "D", explanation: "Apple, Orange, and Banana are fruits. Potato is a tuber/vegetable." },
  "apt_q_49": { answer: "B", explanation: "C = 3*2 = 6. A = 1*2 = 2. B = 2*2 = 4. Sum = 6 + 2 + 4 = 12." },
  "apt_q_50": { answer: "A", explanation: "Logical sequence: Key (1) -> Lock (3) -> Door (2) -> Room (4) -> Switch on (5)." },
  "apt_q_51": { answer: "C", explanation: "Sales in Q2: Alpha (150), Beta (140), Gamma (160). Gamma is highest." },
  "apt_q_52": { answer: "C", explanation: "Rent = 35% of $2000 = 0.35 * 2000 = $700." },
  "apt_q_53": { answer: "C", explanation: "Growth = (5000 - 3000)/3000 = 2000/3000 = 66.7%." },
  "apt_q_54": { answer: "B", explanation: "30% = $15,000 => Total budget = $50,000. Tech budget = 40% of $50,000 = $20,000." },
  "apt_q_55": { answer: "A", explanation: "Handshakes = nC2 = 5 * 4 / 2 = 10." },
  "apt_q_56": { answer: "B", explanation: "Profit = 0.25 * 80000 = $20000. Revenue = 80000 + 20000 = $100,000." },
  "apt_q_57": { answer: "B", explanation: "Average of Student B = (70 + 80) / 2 = 75." },
  "apt_q_58": { answer: "C", explanation: "Total produced = 240 * 8 = 1920. Defective = 1920 * 0.025 = 48." },
  "apt_q_59": { answer: "B", explanation: "Rate of work: 3 painters paint 3 houses in 3 days => 1 painter paints 1 house in 3 days." },
  "apt_q_60": { answer: "A", explanation: "Speak English or French = 35 + 20 - 10 = 45. Neither = 50 - 45 = 5." },
  "apt_q_61": { answer: "B", explanation: "Let train length = L. Speed = L/6. Platform formula: Speed = (L+100)/10. L/6 = (L+100)/10 => 10L = 6L + 600 => 4L = 600 => L = 150m." },
  "apt_q_62": { answer: "B", explanation: "Milk left = 80 * (1 - 8/80)^2 = 80 * (0.9)^2 = 80 * 0.81 = 64.8 liters." },
  "apt_q_63": { answer: "B", explanation: "Total worker-hours = 4 * 2 = 8. Packing rate = 40 boxes / 8 worker-hours = 5 boxes/hour." },
  "apt_q_64": { answer: "B", explanation: "Reduction % = [R / (100 + R)] * 100 = (25 / 125) * 100 = 20%." },
  "apt_q_65": { answer: "A", explanation: "Sample space: BB, BG, GB (GG excluded since at least one is a boy). Favorable: BB. Probability = 1/3." },
  "apt_q_66": { answer: "B", explanation: "To abandon means to desert, leave, or give up." },
  "apt_q_67": { answer: "A", explanation: "Loquacious means talkative; the opposite is silent or taciturn." },
  "apt_q_68": { answer: "B", explanation: "'Each' is singular, so it should be 'has completed' instead of 'have completed'." },
  "apt_q_69": { answer: "A", explanation: "Logical flow: Define Carbohydrates first (Q) -> Describe what they include (R) -> Explain their role (P). So, Q, R, P." },
  "apt_q_70": { answer: "A", explanation: "The preposition 'on' always follows the adjective 'keen' in this context." },
  "apt_q_71": { answer: "B", explanation: "The correct spelling is 'Accommodation' with double 'c' and double 'm'." },
  "apt_q_72": { answer: "A", explanation: "Subject and Object swap; past tense 'cooked' becomes 'was cooked'." },
  "apt_q_73": { answer: "B", explanation: "The idiom 'spill the beans' means to reveal secret information prematurely." },
  "apt_q_74": { answer: "A", explanation: "Using deductive reasoning: Oak is a subset of trees, all trees need water, therefore oak needs water." },
  "apt_q_75": { answer: "B", explanation: "Ephemeral means short-lived; the opposite is permanent or everlasting." },
  "apt_q_76": { answer: "A", explanation: "'Neither' is a singular pronoun and takes a singular verb ('is')." },
  "apt_q_77": { answer: "B", explanation: "Burning the midnight oil means working late into the night." },
  "apt_q_78": { answer: "B", explanation: "Past perfect tense 'had left' describes an action completed before another past action." },
  "apt_q_79": { answer: "B", explanation: "Pragmatic means dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations." },
  "apt_q_80": { answer: "B", explanation: "Subjunctive mood uses 'were' for hypothetical or contrary-to-fact conditions." },
};

export function isCorrect(questionId: string, selected: string): boolean {
  const entry = APTITUDE_ANSWER_KEY[questionId];
  if (!entry) return false;
  return String(selected).trim().toUpperCase() === entry.answer.trim().toUpperCase();
}
